# Generated by Django 3.0.6 on 2020-05-22 20:29

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=51, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=250, null=True)),
                ('access_token', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
