# Generated by Django 3.0.6 on 2020-05-22 20:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_id', models.BigIntegerField(unique=True)),
                ('pick_up_point', models.BooleanField()),
                ('shipment_date', models.DateTimeField(null=True)),
                ('shipment_reference', models.CharField(max_length=50, null=True)),
                ('fulfilment_method', models.CharField(max_length=7, null=True)),
                ('shipment_items', jsonfield.fields.JSONField(default=dict)),
                ('transport', jsonfield.fields.JSONField(default=dict)),
                ('customer_details', jsonfield.fields.JSONField(default=dict)),
                ('billing_details', jsonfield.fields.JSONField(default=dict)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.Shop')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
    ]
